version: 2
updates:

  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"